#!/usr/bin/env python3
import os
import argparse
import sys

ATTACKS = {
    'none': 'no-attack',
    'nxdomain': 'nxdomain-attack',
    'nodata': 'nodata-attack',
    'drop': 'drop-attack',
    'lie': 'lie-attack'
}

parser = argparse.ArgumentParser(description='DNS Attack Selector')
parser.add_argument(
    'attack', help="which DNS attack to apply", choices=ATTACKS.keys())

if __name__ == '__main__':
    if len(sys.argv) == 1:  # No args
        parser.print_help()
        parser.exit()
    attack = parser.parse_args().attack

    try:
        os.remove("/etc/bind/attack.db")
    except OSError:
        pass
    print("creating symlink")
    os.symlink(
        "/etc/bind/{}.db".format(ATTACKS[attack]),
        "/etc/bind/attack.db"
    )
    os.system("systemctl restart bind9")
